language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: xenial
    - dist: bionic
    - os: osx
      brew_packages: hunspell
    - os: osx
      disable_homebrew: true

addons:
  apt:
    packages:
      - libpoppler-cpp-dev
