language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - dist: xenial
    - dist: bionic
    - os: osx
      brew_packages: hunspell
    - os: osx
      disable_homebrew: true
    - r: 3.6
      os: osx
      osx_image: xcode7.3
      disable_homebrew: true
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf

addons:
  apt:
    packages:
      - libpoppler-cpp-dev
